HSLdevcom/digitransit-kubernetes-deploy

- play_setup_aks.yml
- roles/aks-setup/tasks/main.yml
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3104
> added ansible resource provisioning scripts for aks resources

- roles/aks-deployment/files/prod/digitransit-deployer-prod.yml
- roles/aks-deployment/files/prod/digitransit-proxy-prod.yml
- roles/aks-deployment/files/prod/digitransit-ui-hsl-prod.yml
- roles/aks-deployment/files/prod/digitransit-ui-matka-prod.yml
- roles/aks-deployment/files/prod/digitransit-ui-waltti.prod.yml
- roles/aks-deployment/files/prod/hsl-map-server-prod.yml
- roles/aks-deployment/files/prod/hsl-timetable-container-prod.yml
- roles/aks-deployment/files/prod/navigator-server-prod.yml
- roles/aks-deployment/files/prod/opentripplanner-data-con-waltti-prod.yml
- roles/aks-deployment/files/prod/opentripplanner-finland-prod.yml
- roles/aks-deployment/files/prod/opentripplanner-hsl-prod.yml
- roles/aks-deployment/files/prod/opentripplanner-waltti-prod.yml
- roles/aks-deployment/files/prod/pelias-api-prod.yml
- roles/aks-deployment/files/prod/pelias-data-container-prod.yml
- roles/aks-deployment/files/prod/raildigitraffic2gtfsrt-prod.yml
- roles/aks-deployment/files/prod/siri2gtfsrt-prod.yml
Enabled slack, more instances, more cpu to otp's more mem to rails..
> Initial changes to prod yamls

- roles/aks-apply/files/dev/otp-data-builder-dev-dev.yml
- roles/aks-apply/files/dev/otp-data-builder-prod-dev.yml
* Transform otp data builders into CronJobs with priorityclasses to improve resource utilization
> Cronjob otp

- roles/aks-apply/files/dev/pelias-data-container-builder-dev.yml
* Transform pelias-data-container-builder into a CronJob
* Remove DOCKER_API_VERSION env as the default version should work
> Cronjob pelias

- roles/aks-apply/files/dev/digitransit-deployer-dev.yml
- roles/aks-apply/files/dev/hsl-map-server-dev.yml
- roles/aks-apply/files/dev/opentripplanner-waltti-dev.yml
- roles/aks-apply/files/dev/pelias-data-container-dev.yml
- roles/aks-apply/files/dev/raildigitraffic2gtfsrt-dev.yml
- roles/aks-apply/files/dev/yleisviestipalvelu-dev.yml
For deployer, otp waltti pelias data container, raildigitraffic2gtfsrtand yleisviestipalvelu
> Dev mem optimization

- env_vars/dev.yml
- env_vars/prod.yml
- roles/aks-apply/files/dev/digitransit-proxy-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-matka-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-waltti-dev.yml
- roles/aks-apply/files/dev/graphiql-dev.yml
- roles/aks-apply/files/dev/hsl-map-server-dev.yml
- roles/aks-apply/files/dev/opentripplanner-finland-dev.yml
- roles/aks-apply/files/dev/pelias-api-dev.yml
- roles/aks-apply/files/dev/raildigitraffic2gtfsrt-dev.yml
- roles/aks-apply/files/dev/siri2gtfsrt-dev.yml
- roles/aks-apply/files/prod/digitransit-proxy-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-hsl-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-matka-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-waltti-prod.yml
- roles/aks-apply/files/prod/graphiql-prod.yml
- roles/aks-apply/files/prod/hsl-map-server-prod.yml
- roles/aks-apply/files/prod/pelias-api-prod.yml
- roles/aks-apply/files/prod/raildigitraffic2gtfsrt-prod.yml
- roles/aks-apply/files/prod/siri2gtfsrt-prod.yml
* Checked CPU usage in prod and adjusted CPU allocations and replicas based on those findings
* Lessened memory allocation for dev OTP finland as it consumes less data now
> Finetune limits

- roles/aks-apply/files/prod/digitransit-deployer-prod.yml
- roles/aks-apply/files/prod/digitransit-proxy-prod.yml
- roles/aks-apply/files/prod/digitransit-site-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-hsl-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-matka-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-waltti-prod.yml
- roles/aks-apply/files/prod/graphiql-prod.yml
- roles/aks-apply/files/prod/hsl-map-server-prod.yml
- roles/aks-apply/files/prod/hsl-timetable-container-prod.yml
- roles/aks-apply/files/prod/navigator-server-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-finland-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-hsl-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-finland-prod.yml
- roles/aks-apply/files/prod/opentripplanner-hsl-prod.yml
- roles/aks-apply/files/prod/opentripplanner-waltti-prod.yml
- roles/aks-apply/files/prod/pelias-api-prod.yml
- roles/aks-apply/files/prod/pelias-data-container-prod.yml
- roles/aks-apply/files/prod/raildigitraffic2gtfsrt-prod.yml
- roles/aks-apply/files/prod/siri2gtfsrt-prod.yml
- roles/aks-apply/files/prod/yleisviestipalvelu-prod.yml
- roles/aks-apply/files/template.yml
* Add dummy values for lastRestartDate so that the existing value of that label is replaced when manifest is applied.
> Prod dummy values

- roles/aks-apply/files/dev/digitransit-ui-hsl-next-dev.yml
- roles/aks-apply/files/dev/hsl-map-server-next-dev.yml
MAP_PATH_PREFIX to hsl-map-server-next
Note DO NOT Merge and especially DO NOT apply changes untill https://github.com/HSLdevcom/digitransit-proxy/pull/129 is merged!
> DT-3633 again 

- env_vars/dev.yml
- env_vars/prod.yml
- roles/aks-setup/defaults/main.yml
* Moved kubernetes_version to env_vars so different environments can use different kubernetes versions
> Move kubernetes_version to env_vars and upgrade dev version

- README.md
- env_vars/dev.yml
- env_vars/prod.yml
- play_configure_addons.yml
- roles/aks-addons/tasks/main.yml
- roles/aks-apply/tasks/main.yml
- roles/aks-setup/defaults/main.yml
- roles/aks-setup/tasks/main.yml
- tasks/README.md
* Upgraded prod kubernetes version
* Couple of fixes to installing monitoring addon
* Disabled kube-dashboard addon
* Refactored how addons are configured as the az commands finish now before cluster is properly ready and attempts to reconfigure addons will fail before cluster is ready
* Moved kube config update to the end of the addons tasks because it will also fail if the az command is executed too soon after the AKS cluster is created
> Prod version update

- roles/aks-apply/files/prod/digitransit-ui-hsl-next-prod.yml
> local storage emitter config for prod ui hsl

- env_vars/prod.yml
- roles/aks-apply/files/dev/opentripplanner-next-waltti-dev.yml
- roles/aks-apply/files/dev/otp-data-builder-waltti-next-prod-dev.yml
- roles/aks-apply/files/prod/keyvaultsecrets-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-next-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-next-waltti-prod.yml
* Increased memory alloc for next waltti otp as it requires more memory when it builds graph
* Added otp data builder for next waltti prod
* Added prod next waltti routing and routing data containers
> Otp2 prod builder

- roles/aks-apply/files/prod/digitransit-proxy-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-hsl-next-prod.yml
* Unfreeze proxy image
* Change proxy and next ui envs in preparation for release
> Release configuration

- roles/aks-setup/tasks/main.yml
Added uptime SLA command to cluster creation command
> uptime SLA for az aks create

- roles/aks-apply/files/dev/digitransit-ui-waltti-next-dev.yml
- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
- Enable login for waltti cities on next.
> DT-4303: Set up openId clients for waltti id

- env_vars/prod.yml
- roles/aks-apply/files/prod/digitransit-proxy-prod.yml
- roles/aks-apply/files/prod/digitransit-site-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-hsl-next-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-hsl-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-linjasto2021-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-matka-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-waltti-next-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-waltti-prod.yml
- roles/aks-apply/files/prod/hsl-map-server-linjasto2021-prod.yml
- roles/aks-apply/files/prod/hsl-map-server-next-prod.yml
- roles/aks-apply/files/prod/hsl-map-server-prod.yml
- roles/aks-apply/files/prod/hsl-timetable-container-prod.yml
- roles/aks-apply/files/prod/navigator-server-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-finland-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-hsl-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-linjasto2021-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-next-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-data-con-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-finland-prod.yml
- roles/aks-apply/files/prod/opentripplanner-hsl-prod.yml
- roles/aks-apply/files/prod/opentripplanner-linjasto2021-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-next-waltti-prod.yml
- roles/aks-apply/files/prod/opentripplanner-waltti-prod.yml
- roles/aks-apply/files/prod/pelias-api-prod.yml
- roles/aks-apply/files/prod/pelias-data-container-prod.yml
- roles/aks-apply/files/prod/raildigitraffic2gtfsrt-prod.yml
- roles/aks-apply/files/prod/siri2gtfsrt-prod.yml
* Upgrade prod aks version
* Update policy api versions for prod manifests
> Prod update

- roles/aks-apply/files/dev/otp-data-builder-varely-prod-v3-dev.yml
* Added new cronjob task `otp-data-builder-waltti-alt-prod-v3`.
* Job start time 00:30 Helsinki/Europe is scheduled before other production data builders
Related issue: DT-5399
> Add otp-data-builder/prod-v3 for varely

- roles/aks-apply/files/dev/digitransit-ui-hsl-v2-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-hsl-v2-test-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-hsl-v3-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-matka-v2-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-matka-v3-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-waltti-v2-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-waltti-v3-dev.yml
- roles/aks-apply/files/dev/graphiql-dev.yml
- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
- roles/aks-apply/files/dev/pelias-data-container-builder-dev-dev.yml
- roles/aks-apply/files/dev/raildigitraffic2gtfsrt-dev.yml
Required changes for dev api management.
> Api management

- roles/aks-apply/files/dev/otp-data-builder-waltti-dev-v3-dev.yml
> add Pori data as extra_src DT-5822

- roles/aks-apply/files/dev/digitransit-proxy-dev.yml
- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
- Added Raasepori keyvault configurations
> dt-5980 raasepori keyvault config

- roles/aks-apply/files/dev/otp-data-builder-waltti-dev-v3-dev.yml
- Kuopio has specific test data source for development.
> DT-5975 Kuopio dev data as extra_src

- roles/aks-apply/files/dev/otp-data-builder-waltti-dev-v3-dev.yml
- Kuopio test data does not pass tests, so quality tests skipped.
> dt-5975 kuopio data quality tests skipped

- roles/aks-apply/files/dev/digitransit-ui-hsl-v2-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-hsl-v2-test-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-hsl-v3-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-matka-v3-dev.yml
- roles/aks-apply/files/dev/digitransit-ui-waltti-v3-dev.yml
- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
> Citybike scheduler envs

- roles/aks-apply/files/prod/digitransit-ui-hsl-v3-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-matka-v3-prod.yml
- roles/aks-apply/files/prod/digitransit-ui-waltti-v3-prod.yml
- roles/aks-apply/files/prod/keyvaultsecrets-prod.yml
> citybike prod preparation

- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
- keyvaultsecrets for proxy (new waltti test instance)
> DT-6312 keyvaultsecrets

- roles/aks-apply/files/prod/hsl-map-server-prod.yml
- roles/aks-apply/files/prod/pelias-api-prod.yml
- roles/aks-apply/files/prod/pelias-data-container-prod.yml
* Moving pelias and hsl-map-server into new node pool
> DT-6288 part2

- roles/aks-apply/files/dev/otp-data-builder-waltti-dev-v3-dev.yml
- roles/aks-apply/files/dev/otp-data-builder-waltti-prod-v3-dev.yml
Lahti data has digitransit_fare files which must be renamed.
> Lahti fare files renamed

- roles/aks-apply/files/dev/digitransit-ui-waltti-test-dev.yml
- roles/aks-apply/files/dev/otp-data-builder-waltti-alt-v3-dev.yml
- Remove otp url to use UI config instead in next-dev
- Remove extra_src which is already configured in data-container
> Next dev otp url

- roles/aks-apply/files/dev/digitransit-deployer-dev.yml
- roles/aks-apply/files/prod/digitransit-deployer-prod.yml
* Add new permission for deployer
> DT-5798 digitransit-deployer refactor part 1

- roles/aks-apply/files/dev/digitransit-deployer-dev.yml
- roles/aks-apply/files/dev/hsl-timetable-container-dev.yml
- roles/aks-apply/files/dev/keyvaultsecrets-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-finland-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-finland-v3-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-hsl-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-hsl-v3-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-varely-v3-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-waltti-alt-v3-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-waltti-dev.yml
- roles/aks-apply/files/dev/opentripplanner-data-server-waltti-v3-dev.yml
- roles/aks-apply/files/dev/opentripplanner-finland-v2-dev.yml
- roles/aks-apply/files/dev/opentripplanner-hsl-dev.yml
- roles/aks-apply/files/dev/opentripplanner-hsl-v2-dev.yml
- roles/aks-apply/files/dev/opentripplanner-kela-v2-dev.yml
- roles/aks-apply/files/dev/opentripplanner-varely-v2-dev.yml
- roles/aks-apply/files/dev/opentripplanner-waltti-alt-v2-dev.yml
- roles/aks-apply/files/dev/opentripplanner-waltti-v2-dev.yml
- roles/aks-apply/files/dev/pelias-data-container-dev.yml
- roles/aks-apply/files/prod/digitransit-deployer-prod.yml
- roles/aks-apply/files/prod/keyvaultsecrets-prod.yml
* Updates env variables for digitransit-deployer
* Enables image freshness monitoring for some dev deployments through a label addition
> DT-6643 part 1 Add deployment image freshness monitoring

- roles/aks-apply/files/dev/otp-data-builder-waltti-alt-v3-dev.yml
- roles/aks-apply/files/dev/otp-data-builder-waltti-v3-dev.yml
WalttiTest updaters moved to data-container (waltti-alt).
> WalttiTest & Tampere extra configs removed
